teleop_twist_joy_node:
    ros__parameters:
        axis_linear:
            x: 2
        scale_linear:
            x: 0.4

        axis_angular:
            yaw: 0
        scale_angular:
            yaw: 2.5

        require_enable_button: false